### ISSUE TITLE
Debug or I am doing this wrong

### ISSUE THREAD

**Issue by mouse0270** [Darkhax-Minecraft/Cauldron-Recipes#10]
I guess the first question is, how do you use this? As when I click on the recipe in JEI it shows me that Concrete Powder + Cauldron  = Concrete... But nothing I seem to do allows me to actually do this. I can't left or right click on the cauldron with an item in my hand.... throwing the item in the cauldron doesn't appear to do anything...

Looking at the log in both latest.log and craftteaker, night show errors related to this mod... I must be doing something wrong, But I have no idea what it might be.

**Comment by Darkhax** [comment]
The mod is used by filling the cauldron with water and then right clicking the cauldron with the item in your mainhand. Can you share the logs so I can look at the errors?

**Comment by mouse0270** [comment]
Okay, so I was doing it right by trying to right click on the cauldron. I've attached the log here.

[latest.log](https://github.com/Darkhax-Minecraft/Cauldron-Recipes/files/5882634/latest.log)

**Comment by mouse0270** [comment]
To be clear, now that I have confirmed how it works. I am going to start figuring out which mod might be causing a conflict. I just didn't have a way to know how it would work. For example, right clicking or, did I throw it in

**Comment by Darkhax** [comment]
The log doesn't have any errors related to this mod. I am guessing it's a conflict with the caves and cliffs update mod as they replace the cauldron with their own. 

> [14:36:28] [Render thread/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `cauldron`, expected `cavesandcliffs`. This could be a intended override, but in most cases indicates a broken mod.

**Comment by mouse0270** [comment]
I am actually testing those two mods together right now. Give me a few minutes and I will update you. I wonder what that mod changes about cauldrons.

**Comment by mouse0270** [comment]
It is the caves and cliffs mod.
