### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by SentientToast1** [Darkhax-Minecraft/Cauldron-Recipes#7]
add a way to change the colour of the cauldron and if possible add multi input(or is it already there?).

**Comment by Darkhax** [comment]
Hello, thanks for the suggestion. My goal for this mod was to change as little of the vanilla mechanics as possible. This makes it easier for vanilla clients, and even bedrock players to use the mod if it is installed on the server. So things like changing the color of the water, custom fluids, or additional data are not things I want to add. There are other mods available which replace the cauldron in more complex ways. 

I may add the option for a second ingredient using the off-hand slot though.

**Comment by SentientToast1** [comment]
ok then but pls add the second ingredient option

**Comment by SentientToast1** [comment]
also could u make it that even in creative u use the item because when i was using it and when i rightclicked with coal it didnt get used up.

**Comment by Darkhax** [comment]
I will consider the offhand item, however not taking items in creative mode is part of how the game works. Things like vanilla buckets also do this. It is intentional.

**Comment by SentientToast1** [comment]
I know but this is a ‘crafting’ mod and in vanilla when u craft something even if u are in creative the items get used up. Referring to brewing stand, crafting table, and furnance

**Comment by Darkhax** [comment]
Those are all GUI based crafting. In world crafting such as bottles, buckets, and fish buckets do not consume the items.

**Comment by SentientToast1** [comment]
well, your mod so now i will stop replying and let u focus on the mod
