### ISSUE TITLE
server crash using 35.0.18

### ISSUE THREAD

**Issue by BedrockLegends** [Darkhax-Minecraft/Cauldron-Recipes#8]
[crash-2020-11-15_11.32.31-fml.txt](https://github.com/Darkhax-Minecraft/Cauldron-Recipes/files/5542813/crash-2020-11-15_11.32.31-fml.txt)

**Comment by Darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/Cauldron-Recipes/commit/3a26b58bbccc8f011142c29b1e83e78b288467b3
