### ISSUE TITLE
Cauldron Recipes has failed to load correctly

### ISSUE THREAD

**Issue by Thorazz** [Darkhax-Minecraft/Cauldron-Recipes#9]
Hello,
when i tried to use this mod the following exception appeared:
// Exception message: java.lang.ClassNotFoundException: 
// net.darkhax.bookshelf.registry.RegistryHelper

I am using the forge version 1.16.4 - 35.1.7 and am using a whole buch off other mods too (list available in crash report).

Please reach out to me if you require more information.
Have a nice day :D

The log and crash report are attached below.
[crash-2020-12-02_15.39.15-fml.txt](https://github.com/Darkhax-Minecraft/Cauldron-Recipes/files/5630007/crash-2020-12-02_15.39.15-fml.txt)
[latest.log](https://github.com/Darkhax-Minecraft/Cauldron-Recipes/files/5630008/latest.log)

**Comment by Darkhax** [comment]
Hello, 

You're missing the mod [Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf). It's listed as a dependency on the CurseForge page.
